### ISSUE TITLE
interlaced video bad for voctocore 

### ISSUE THREAD

**Issue by CarlFK** [CarlFK/voctomix-outcasts#21]
(11:17:38 AM) ivodd: it seems vocto is very peculiar about the exact format of the video coming in
(11:17:53 AM) ivodd: the video I tried had different interleaving
(11:17:53 AM) tumbleweed: are you talking about the interlaced example we spoke about here?
(11:18:07 AM) tumbleweed: that just needed to be deinterlaced before injection
(11:18:09 AM) ivodd: and after that, that specific input didn't work anymore, until voctocore was restarted

**Comment by CarlFK** [comment]
fixed with yadif, then fixed better with deinterlace.

**Comment by stefanor** [comment]
The test video that triggered this report does not pass correctly through the deinterlace filter. It gets corrupted. yadif, on the other hand, works.

**Comment by stefanor** [comment]
The underlying bug here was: https://bugzilla.gnome.org/show_bug.cgi?id=787206
Backporting that patch to buster fixes it there.

yadif worked around it, by fixing the caps. Not necessarily anything else.

A reasonable workaround on buster is to insert `capssetter caps=video/x-raw,interlace-mode=progressive` at the front of the video elements.
